clc
clear all
a = load('~/.ros/time_debug.txt');
spiral = load('~/.ros/spiral_debug.txt');
verify = load('~/.ros/verify_debug.txt');

figure
plot(a(:,1))
legend('befo time')
figure
plot(a(:,2))
legend('model update time')

figure
hold on
for i = 3:19+3
    plot(a(:,i))
end
legend( ...
  'assemble approach action server', ... 
  'assemble spiral action server', ... 
  'assemble insert action server', ... 
  'assemble verify action server', ... 
  'joint trajectory action server', ... 
  'assemble move action server', ... 
  'assemble dual spiral action server', ... 
  'assemble dual approach action server', ... 
  'assemble rotation action server', ... 
  'assemble triple recovery action server', ... 
  'assemble approach bolt action server', ... 
  'assemble retreat bolt action server', ... 
  'task space move action server', ... 
  'assemble probe edge action server', ... 
  'assemble triple move action server', ... 
  'assemble approach hip action server', ... 
  'assemble kitting action server', ... 
  'assemble back forth action server', ... 
  'assemble bolting ready action server')